# Generated by Django 3.0.3 on 2020-05-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
