# Generated by Django 3.0.3 on 2020-05-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
